### ISSUE TITLE
词汇修订与补充

### ISSUE THREAD

**Issue by CoolguyNH** [JX3BOX/jx3box-dict#2]
**词汇列表**
松烟竹雾 — 松煙竹霧
![松](https://user-images.githubusercontent.com/94557850/142251287-3763684a-2902-44dc-bc56-6ea6094ddb8c.png)

游戏里的：
![松烟竹雾](https://user-images.githubusercontent.com/94557850/142251225-be732826-72e6-4ed4-89f6-cc451af923a2.png)

**Comment by iRuxu** [comment]
[f31faf88c5dae01a5d2b1c9ed672ab1be1274201](https://github.com/JX3BOX/jx3box-dict/commit/f31faf88c5dae01a5d2b1c9ed672ab1be1274201)

**Comment by iRuxu** [comment]
可能需要重新創建技能詞庫，暫時推遲部署
