### ISSUE TITLE
词汇修订与补充

### ISSUE THREAD

**Issue by WUSISANERYI** [JX3BOX/jx3box-dict#3]
**词汇列表**
浮游天地 - 浮游天地
松烟竹雾 - 松煙竹霧
百里追魂 - 百里追魂
舍身诀 - 捨身訣
舍身弘法 - 捨身弘法
斗转星移 - 斗轉星移
![圖片](https://user-images.githubusercontent.com/94557922/142255795-8450a48d-e374-46b2-862c-97aee073bf98.png)

**Comment by iRuxu** [comment]
https://github.com/JX3BOX/jx3box-dict/commit/f31faf88c5dae01a5d2b1c9ed672ab1be1274201

**Comment by iRuxu** [comment]
可能需要重新創建技能詞庫，暫時推遲部署

**Comment by WUSISANERYI** [comment]
魔盒宏庫内置簡繁轉換未同步
![圖片](https://user-images.githubusercontent.com/94557922/142603658-2c9b4f35-87d7-40ea-9042-47c831a3caa9.png)
